# 머신러닝 데이터 살펴보기

## 6.1. 사용할 데이터 소개


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets


In [8]:
raw_boston = datasets.load_boston()
X_boston = pd.DataFrame(raw_boston.data)
y_boston = pd.DataFrame(raw_boston.target)
df_boston = pd.concat([X_boston, y_boston], axis=1)
df_boston.head()

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12    0   
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [2]:
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]
        
# raw_boston = datasets.load_boston()
X = data
y = target

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=7)


In [3]:
std_scale =  StandardScaler()
X_train_std = std_scale.fit_transform(X_train)
X_test_std = std_scale.transform(X_test)

clf_linear = LinearRegression()
clf_linear.fit(X_train_std, y_train)

pred_linear = clf_linear.predict(X_test_std)
mean_squared_error(y_test, pred_linear)

29.515137790197585

In [6]:
from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=7)

linear_pipline = Pipeline([
    ('scaler', StandardScaler()),
    ('linear_regression', LinearRegression()),
])

linear_pipline.fit(X_train, y_train)
pred_linear = linear_pipline.predict(X_test)
mean_squared_error(y_test, pred_linear)

29.515137790197585

In [11]:
from sklearn import datasets
raw_iris = datasets.load_iris()
X = raw_iris.data
y = raw_iris.target

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
std_scale = StandardScaler()
std_scale.fit(X_train)
X_train_std = std_scale.transform(X_train)
X_test_std = std_scale.transform(X_test)
clf_knn = KNeighborsClassifier(n_neighbors=2)
clf_knn.fit(X_train_std, y_train)

knn_pred = clf_knn.predict(X_test_std)
print(knn_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 1 2 0 0 0 0 1 0 0 2 1
 0]


In [12]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, knn_pred)
print(accuracy)

0.9736842105263158


In [13]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test, knn_pred)
print(conf_matrix)

[[15  0  0]
 [ 0 11  0]
 [ 0  1 11]]


In [15]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test, knn_pred)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.92      1.00      0.96        11
           2       1.00      0.92      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

